version: '3.9'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:latest-jdk17
    container_name: jenkins-jre-17
    user: 1000:980
    ports:
      - 8200:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      TZ: Asia/Shanghai
