version: "3.9"
services:
  mysql:
    image: mysql:8.0.21
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: rootmima
    ports:
      - 3306:3306
    volumes:
      # 数据挂载
      - ./mysql/data/:/var/lib/mysql/
      # 配置挂载
      - ./mysql/conf/:/etc/mysql/conf.d/
    command: ["--max_connections=1000","--lower_case_table_names=1","--binlog_expire_logs_seconds=3600","--secure-file-priv=/var/lib/mysql"]
  redis:
    image: redis:7.0.8
    restart: always
    volumes:
     - ./redis/conf/redis.conf:/etc/redis/redis.conf
     - ./redis/data:/data
    ports:
     - 6379:6379
