version: "3.9"
services:
  mysql:
    image: mysql:8.0.21
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: rootmima
      LANG: C.UTF-8
    ports:
      - 3326:3306
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/conf/:/etc/mysql/conf.d/
    command: ["--max_connections=1000","--lower_case_table_names=1","--binlog_expire_logs_seconds=3600","--secure-file-priv=/var/lib/mysql"]
    networks:
      - net
  redis:
    image: redis:7.0.8
    volumes:
     - ./redis/conf/redis.conf:/etc/redis/redis.conf
     - ./redis/data:/data
       #ports:
       # - 8379:6379
    networks:
      - net
networks:
  net:
    driver: bridge