version: "3.9"
services:
  mysql:
    image: mysql:8.0.21
    container_name:
      mysql8-1
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: rootmima
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/conf/:/etc/mysql/conf.d/
    command: ["--max_connections=1000","--lower_case_table_names=1","--binlog_expire_logs_seconds=3600","--secure-file-priv=/var/lib/mysql"]
    networks:
      - net
  redis:
    image: redis:7.2.4
    container_name:
      redis7
    volumes:
     - ./redis/conf:/etc/redis
     - ./redis/data:/data
    ports:
     - 6379:6379
    networks:
      - net
    command: ["redis-server", "--requirepass", "your_password"]
  minio:
    image: quay.io/minio/minio
    container_name:
      minio
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data
    networks:
      - net
networks:
  net:
    driver: bridge